# Generated by Django 5.2.1 on 2025-06-02 19:29

import cloudinary.models
import myapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_image_alter_offer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default-category.jpg', storage=myapp.storage.LowQualityCloudinaryStorage(), upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(storage=myapp.storage.LowQualityCloudinaryStorage(), upload_to='offer_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=myapp.storage.LowQualityCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='socialoffer',
            name='gif',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
