# Generated by Django 5.2.1 on 2025-05-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.FileField(upload_to='social_gifs/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_offers', to='myapp.product')),
            ],
        ),
    ]
